{'current_phase': 1,
 'location': {'farm': 'OpenAgBloom', 'field': 'GBE_D_3'},
 'name': 'Trial_3',
 'recipe':{'name':'marsfarm_photoperiod_16/10'}
 'phases': [{'lights': {'off': {'cmd': 'LIGHT_OFF',
                                'setting': {'B': 100,
                                            'G': 100,
                                            'R': 100,
                                            'W': 100},
                                'time': '20:00'},
                        'on': {'cmd': 'LIGHT_ON',
                               'setting': {'B': 75, 'G': 75, 'R': 75, 'W': 75},
                               'time': '8:00'}},
             'name': 'Week 1-2',
             'start_date': None,
             'temperature': 25},
            {'lights': {'off': {'cmd': 'LIGHT_OFF',
                                'setting': {'B': 100,
                                            'G': 100,
                                            'R': 100,
                                            'W': 100},
                                'time': '20:00'},
                        'on': {'cmd': 'LIGHT_ON',
                               'setting': {'B': 75, 'G': 75, 'R': 75, 'W': 75},
                               'time': '8:00'}},
             'name': 'Week 3-4',
             'start_date': None,
             'temperature': 20}],
 'plot': [[1, 2, 4], [3, 6, 5]],
 'plants':{'Brassica rapa':{'plot':[1,3,6]},
           'Extra Dwarf Bok Choy':{'plot':[2, 5]},
           'Kitzawa Seeds':{'plot':[4]}
           },
 'status': {'comment': 'Test trial', 'status': 'In Process'},
 'time': {'start_date': 1625112000.0, 'start_date_str': '2021-07-01 00:41'}}